### ISSUE TITLE
User testing 1 (02/17)

### ISSUE THREAD

**Issue by Jacob-Griffin** [Jacob-Griffin/TelephonePictionary2.0#12]
- [x] Right click behavior is weird on canvas
- [x] Name sorting does not use locale, A < Z < a < z
- [ ] Consider modifying "excess review buttons" behavior (#14)
- [x] Icons for Game controls (Minimum viable, opening #15 to track better icons)
- [x] Limitations on players
- [x] Limitations on time
- [x] Finish removing "is ready" for the lobby
- [x] Defaults for empty submissions

**Comment by melindamorang** [comment]
- [x] Allow "None" as an option for time limit
- [ ] Consider updating the endgame stack review to a scrolling vertical layout instead of a side-to-side slideshow.  It worked beautifully, but some people preferred being able to see the whole stack at once to enjoy its evolution.

**Comment by Jacob-Griffin** [comment]
All tasks that are unique to this issue are handled. All outstanding tasks are being tracked on #14. Closing this issue to declutter.
