### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by Jacob-Griffin** [Jacob-Griffin/TelephonePictionary2.0#6]
Evaluate whether or not we need a footer, or if we should put the information somewhere else.

My current thought is maybe putting the footer as-is but only on the home page, that way it's out of the way during gameplay/review and still allows me to make a single-screen / non-scrolling layout for desktop widths

**Comment by melindamorang** [comment]
The "log an issue" thing currently lives in the footer, and it seems like people would be most likely to encounter an issue during gameplay. That said, nobody has _ever_ logged an issue.

**Comment by Jacob-Griffin** [comment]
I've decided to create a footer that's currently home page only, and displays just the copyright and attribution since logging an issue is apparently not a pressing need. I think we probably should on including submit an issue again eventually, but maybe as a separate ui element, and after a few more things are ready:

- Issue templates
- Cleared up enough of our outstanding issues from the initial batch
