### ISSUE TITLE
Single-page / Non-Scrolling Layout

### ISSUE THREAD

**Issue by Jacob-Griffin** [Jacob-Griffin/TelephonePictionary2.0#7]
During a column view of the gameplay, to make the incoming card match the style of the outgoing card/player input, we either need to have small cards for both (not enough drawing room) or big cards for both (Have to scroll back and forth). In a mobile browser, this is no issue because max-width is going to kick in and they'll be as wide as possible anyway, so no worries, but desktop view is torn between two not great design choices.

We need a layout that allows desktop users the space to draw without needing to scroll back and forth to reference the prompt. By rejecting the column layout for big enough screens, we can also accept differing sizes for input/output or image/text

### Layout Acceptance Criteria:

- [ ] Any Drawing inputs will fill a majority of the space available.
- [ ] Any image prompts will be legible at scale
- [ ] Comfortably fits all text prompts up to the character limit in both input and output
- [ ] Players can easily identify where their prompt is and where their input is
- [ ] This can be achieved with no scrolling

And of course implementation should appropriately decide when to use this layout. No display left behind (except *really* small ones)

**Comment by melindamorang** [comment]
For a very large desktop screen, I don't really think we'd need to use the full width for the canvas.  Maybe the prompt text could get placed side-by-side with the canvas.

Why do we need the incoming prompt text to be a "card" at all?  Why not just give it to them in a different, more compact format?  Most of the card space is kind of wasted or empty anyway, after all.

**Comment by Jacob-Griffin** [comment]
Details in a comment on #25, I came up with a layout that just needs more testing, but should meet these requirements

**Comment by Jacob-Griffin** [comment]
With the addition of a layout for mobile drawing this is pretty much as complete as it can be short of a few issues that are covered elsewhere. Closing as complete
